### ISSUE TITLE
Useful function not working

### ISSUE THREAD

**Issue by lidefi87** [aodn/rimrep-training#17]
function ccccccc is not doing xxxxx and tried xyz,
this is the error:
kkkkkkk

this is my code:
eeeee

**Comment by diodon** [comment]
Could you please provide an example of what you are actually trying to do?

**Comment by lidefi87** [comment]
more details

**Comment by lidefi87** [comment]
https://github.com/aodn/rimrep-training/blob/main/RHR_training_May2024/R_notebooks/API_data_access.Rmd

**Comment by lidefi87** [comment]
@diodon 
more info here

**Comment by lidefi87** [comment]
test
